service: serverless-plugin-sqs-local-example-config

plugins:
  - '@serverless-plugin-sqs-local/serverless-plugin-sqs-local'
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

custom:
  serverless-plugin-sqs-local:
    elasticmq:
      setup:
        downloadUrl: 'https://s3-eu-west-1.amazonaws.com/softwaremill-public/elasticmq-server-0.13.8.jar'
        installPath: '.ElasticMQ'
      start:
        port: ${env:SQS_PORT}

functions:
  ping:
    handler: handler.ping
    events:
      - http:
          path: ping
          method: get
  pong:
    handler: handler.pong
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - SQSQueuePing
              - Arn

resources:
  Resources:
    SQSQueuePing:
     Type: AWS::SQS::Queue
     Properties:
       QueueName: ping
