service: serverless-plugin-sqs-local-example

plugins:
  localPath: '../../packages/serverless-plugin-sqs-local'
  modules:
    - '@serverless-plugin-sqs-local/serverless-plugin-sqs-local'
    - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'

functions:
  ping:
    handler: handler.ping
    events:
      - http:
          path: ping
          method: get
  pong:
    handler: handler.pong
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - SQSQueuePing
              - Arn

resources:
  Resources:
    SQSQueuePing:
     Type: AWS::SQS::Queue
     Properties:
       QueueName: ping
